[sncast.default]
url = "https://free-rpc.nethermind.io/sepolia-juno/v0_7"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "deployer"
[sncast.true]
account = "myaccount"
accounts-file = "/home/amir/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = ""
